name: Infra - Apply (Terraform)

on:
  push:
    branches: ["main"]
    paths:
      - "infra/terraform/**"

jobs:
  apply_staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout (GitHub Action)
        uses: actions/checkout@v4

      - name: Setup Terraform (GitHub Action)
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (Terraform CLI)
        working-directory: infra/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform Apply - Staging (Terraform CLI)
        working-directory: infra/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve -var-file=envs/staging.tfvars

